version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - node_modules_cache
    environment:
      - CHOKIDAR_USEPOLLING=true

  node_modules_cache:
    image: node:18
    command: echo "Node modules cache"
    volumes:
      - /app/node_modules
